version: '2'
services:
  web:
    build: .
    container_name: phpolo-api 
    mem_limit: 1g
    volumes:
     - ./:/var/www/phpolo
     - ./log/:/var/log/apache2
    restart: always
    networks:
      static-network:
        ipv4_address: 172.30.0.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          ip_range: 172.31.5.0/24
